baseURL = "https://www.linkedin.com/in/lukebottomley/"
title = "an-architects-journey"
paginate = 5
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
googleAnalytics = "UA-123-45"
pygmentsUseClasses = true

disqusShortname = 'an-architects-journey'   # use disqus comments

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "an-architects-journey"
description = "A blog about Salesforce, architecture and personal development"
keywords = [ "Blog", "Portfolio", "PaperMod","Salesforce", "Architecture"]
author = "Luke Bottomley"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = true
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false

  [params.assets]
  favicon = "<link / abs url>"
  favicon16x16 = "<link / abs url>"
  favicon32x32 = "<link / abs url>"
  apple_touch_icon = "<link / abs url>"
  safari_pinned_tab = "<link / abs url>"

  [params.label]
  text = "Home"
  icon = "/apple-touch-icon.png"
  iconHeight = 35

  [params.profileMode]
  enabled = true
  title = "An Architect's Journey"
  subtitle = "A site where you'll find posts about Salesforce, consultancy & personal growth, usually from me, sometimes from others. Built using Hugo and hosted using Github to test my skills"
  imageUrl = "https://media.licdn.com/dms/image/D4E03AQGrI5inukzejw/profile-displayphoto-shrink_800_800/0/1676968817691?e=1710374400&v=beta&t=k7A2hlzcn5hTQMTeCiUqNXfK18GLB3f1CwsCqkKK7HI"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Posts"
    url = "posts"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Hello & Welcome to my blog 👋."
  Content = "Here you'll find posts about Salesforce, Consultancy & personal growth, usually from me, sometimes from others. Built using Hugo and hosted using Github to test my skills."

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/lukebottomley/"

[params.analytics.google]
SiteVerificationTag = "XYZabc"

[params.analytics.bing]
SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.editPost]
  URL = "https://github.com/botbot-priv/botbot-priv.github.io/blob/master/content/"
  Text = "Suggest Changes"
  appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "categories"
name = "categories"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 20

[markup.highlight]
noClasses = false
